services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: etoh-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: etoh_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d etoh_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Express API Backend
  api:
    build: ./backend
    container_name: etoh-api-dev
    restart: unless-stopped
    user: "1001:1001"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=etoh_tracker
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_DIR=/app/uploads
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - uploads_data:/app/uploads
      - ./backend:/app  # Live reload for development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # Expo React Native App (Development)
  app:
    build:
      context: .
      args:
        API_URL: ${API_URL:-http://localhost:3001}
    container_name: etoh-app-dev
    restart: unless-stopped
    ports:
      - "19006:80"  # Map container port 80 to host port 19006
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data: