version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: etoh-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: etoh_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d etoh_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Express API Backend
  api:
    build: ./backend
    container_name: etoh-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=etoh_tracker
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # Expo React Native App
  app:
    build: .
    container_name: etoh-app
    restart: unless-stopped
    ports:
      - "19006:80"
    environment:
      - API_URL=http://localhost:3001
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: