data_dir: /var/lib/vector

sources:
  docker_logs:
    type: docker_logs

transforms:
  filter_logs:
    type: filter
    inputs:
      - docker_logs
    condition:
      type: vrl
      source: |
        .label."com.docker.compose.service" != null

sinks:
  prometheus:
    type: prometheus_exporter
    inputs:
      - filter_logs
    address: 0.0.0.0:9001